
FROM ubuntu:latest
RUN apt-get update && apt-get install python3-pip -y
# Install any needed packages specified in requirements.txt
# RUN pip install paho-mqtt opencv-python
# Install Ultralytics' YOLOv5
# RUN pip install ultralytics

ADD YoloWithWebCam.py YoloWithWebCam.py
CMD python3 YoloWithWebCam.py