
FROM ubuntu:latest
RUN apt-get update && apt-get install python3-pip -y
ADD FirstTestWebCam.py FirstTestWebCam.py
ADD PublishToTopic.py PublishToTopic.py
ADD RecieveMessageAndSaveToDataBase.py RecieveMessageAndSaveToDataBase.py
ADD YoloWithWebCam.py YoloWithWebCam.py
CMD python3 YoloWithWebCam.py